### ISSUE TITLE
Error: Failed to load the JS script of the agent

### ISSUE THREAD

**Issue by bohdanKatiukha** [fingerprintjs/fingerprintjs-pro-angular#45]
Hello, I get this error:
Error: Failed to load the JS script of the agent

We're on version
"@fingerprintjs/fingerprintjs-pro-angular": "1.1.0"

There is a problem with AdBlock, can you help me with solution, maybe there is a couple of ways to fix it (proxy integration it`s best but not in my case)

**Comment by JuroUhlar** [comment]
Hi, @bohdanKatiukha. Yes, ad blockers can disrupt API requests to Fingerprint domains. The recommended solution is using cloud proxy integrations to route all Fingerprint traffic through your domain. You can learn more here: https://dev.fingerprint.com/docs/protecting-the-javascript-agent-from-adblockers 

May I ask what is preventing you from using a cloud proxy integration? Another potential solution is to work with our [support team](https://fingerprint.com/support) to host and continually update the JS agent script yourself. In practice, this can lead to users missing important JS Agent updates, lowering the effectiveness of visitor identification, so we do not generally recommend it.

**Comment by lizongxiao** [comment]
> Hi, @bohdanKatiukha! Yes, ad blockers can disrupt API requests to Fingerprint domains. The recommended solution is using cloud proxy integrations to route all Fingerprint traffic through your domain. You can learn more here: https://dev.fingerprint.com/docs/protecting-the-javascript-agent-from-adblockers你好， ！是的，广告拦截器可以中断对指纹域的 API 请求。推荐的解决方案是使用云代理集成来路由通过您的域的所有指纹流量。您可以在这里了解更多信息：https://dev.fingerprint.com/docs/protecting-the-javascript-agent-from-adblockers
> 
> May I ask what is preventing you from using a cloud proxy integration? Another potential solution is to work with our [support team](https://fingerprint.com/support) to host and continually update the JS agent script yourself. In practice, this can lead to users missing important JS Agent updates, lowering the effectiveness of visitor identification, so we do not generally recommend it.请问是什么阻止您使用云代理集成？另一个潜在的解决方案是与我们的支持团队合作，自行托管并不断更新 JS 代理脚本。实际上，这可能会导致用户错过重要的 JS Agent 更新，从而降低访客识别的有效性，因此我们一般不推荐这样做。
> 
> Have a nice day!祝你今天过得愉快！

it works when i prevent ad plugin, thanks.
